# Generated by Django 5.2.3 on 2025-06-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs_limit', models.IntegerField(default=20)),
                ('venue', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('toss_decision', models.CharField(blank=True, choices=[('bat', 'Bat'), ('bowl', 'Bowl')], max_length=10, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='teams.team')),
                ('toss_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_toss_matches', to='teams.team')),
            ],
        ),
    ]
