# Generated by Django 5.2.3 on 2025-06-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('scoreboard', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('ball_type', models.CharField(choices=[('normal', 'Normal'), ('wide', 'Wide'), ('no_ball', 'No Ball'), ('bye', 'Bye'), ('leg_bye', 'Leg Bye')], default='normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_events', to='teams.player')),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling_events', to='teams.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
