# Generated by Django 5.2.3 on 2025-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_department_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='games',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('basketball', 'Basketball'), ('cricket', 'Cricket')], max_length=20),
        ),
    ]
