"""
Django settings for sangathan_backend project.
Generated by 'django-admin startproject' using Django 5.2.3.
"""

import os
from pathlib import Path

# --------------------------------------
# BASE PATHS
# --------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------
# SECURITY
# --------------------------------------
SECRET_KEY = 'django-insecure-Db0223acde17e9174db3a2800b7081359'  # 🔐 Replace for production
DEBUG = True  # ❗Turn OFF in production

ALLOWED_HOSTS = [
    "127.0.0.1", 
    "localhost",
    "amity-sangathan.onrender.com",
    "www.amity-sangathan.onrender.com"
]

# --------------------------------------
# APPLICATIONS
# --------------------------------------
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'participants',
    'matches',
    'scoreboard',
    'contact',
    'accounts',
    

    # Auth and Social login
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1

# --------------------------------------
# AUTHENTICATION BACKENDS
# --------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

AUTH_USER_MODEL = 'accounts.CustomUser'  # ✅ Custom user model
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]


# --------------------------------------
# ALLAUTH SETTINGS (Google login only)
# --------------------------------------

ACCOUNT_SIGNUP_FIELDS = []  # No form fields on signup
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_FORMS = {}
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'

# --------------------------------------
# ALLAUTH CONFIG (new syntax - post 0.61)
# --------------------------------------

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}  # Using email-only login

ACCOUNT_FORMS = {}
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'

LOGIN_URL = '/accounts/google/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/profile-check/'


# Optional login redirection
LOGIN_URL = '/accounts/google/login/'
LOGIN_REDIRECT_URL = '/complete_profile/'
LOGOUT_REDIRECT_URL = '/'

# --------------------------------------
# EMAIL (for development)
# --------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --------------------------------------
# MIDDLEWARE
# --------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files on render.com
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required by allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------
# URLS / TEMPLATES / WSGI
# --------------------------------------
ROOT_URLCONF = 'sangathan_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Required by allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sangathan_backend.wsgi.application'

# --------------------------------------
# DATABASE (SQLite for now)
# --------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}

# --------------------------------------
# PASSWORD VALIDATORS
# --------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------
# LOCALIZATION
# --------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# --------------------------------------
# STATIC FILES (for deployment)
# --------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --------------------------------------
# DEFAULT AUTO FIELD
# --------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
